/*
 * Generated by PEG.js 0.10.0.
 *
 * http://pegjs.org/
generate grammar with :
  • pegjs --format globals maxlang-grammar.pegjs

  • add this at begin and end

in max js use it with :

var req = require("maxlang-grammar");

post(req.PARSER.parse('additive'))

*/


exports.PARSER = /*
 * Generated by PEG.js 0.10.0.
 *
 * http://pegjs.org/
 */
(function() {

.......

return {
  SyntaxError: peg$SyntaxError,
  parse:       peg$parse
};
})();
